version: '3.3'

services:
  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    hostname: db.${PUBLIC_DOMAIN}
    env_file: ./.env                                                 # Environment file with settings
    volumes:
      - leantime_public_userfiles:/var/www/html/public/userfiles     # Volume to store public files, logo etc
      - leantime_userfiles:/var/www/html/userfiles                   # Volume to store private user uploaded files
    ports:
      - "${LOCAL_ADDRESS}:20080:80"                                  # The port to expose and access Leantime
volumes:
  leantime_userfiles:
    name: "devbelt-leantime-userfiles"
  leantime_public_userfiles:
    name: "devbelt-leantime-public-userfiles"